# Generated by Django 5.0.6 on 2024-07-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Madera', 'Madera'), ('Bazar', 'Bazar'), ('Deco', 'Deco')], max_length=100),
        ),
    ]
